server:
  port: 9042

logging:
  level:
    root: INFO

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  http:
    multipart:
      enabled=false:
  application:
    name: server
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gpnu_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "123456"

custom:
  hadoop:
    rm:
      uri: localhost:8088
    nn:
      uri: localhost:50070
    conf: C:\Users\Yue.Zeng\Documents\GPNU\core\src\main\resources
    proxyuser: root
    hivemetastore: thrift://localhost:9083
  task:
    packageDir: C:\Users\Yue.Zeng\Documents\GPNU\server\src\main\resources\packages
    azkaban:
      server: localhost:8081
      user: azkaban
      password: azkaban
      execHome: C:\Users\Yue.Zeng\Documents\GPNU\server\src\main\resources\azkaban-exec-server
    api:
      server: localhost
      port: "9042"
  presto:
    uri: jdbc:presto://localhost:9090/hive
  hive:
    uri: jdbc:hive2://localhost:10000/default
  spark:
    home: C:\Users\Yue.Zeng\Documents\GPNU\server\src\main\resources\spark-2.4.4-bin-hadoop2.7
  redis:
    ip: 127.0.0.1
    port: 6379
  ranger:
    url: http://localhost:6080
    user: admin
    pwd: admin
    service:
      hdfs: imooc_hdfs
      hive: imooc_hive